# Generated by Django 5.2.4 on 2025-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateTimeField(auto_now_add=True, default="2025-07-22"),
            preserve_default=False,
        ),
    ]
